// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQk19EcNUt3xOYK7iC97NoaOcfFD-y5qA',
    appId: '1:123604383744:web:3eefb938ef2f2380d840e5',
    messagingSenderId: '123604383744',
    projectId: 'footrank-14e9a',
    authDomain: 'footrank-14e9a.firebaseapp.com',
    storageBucket: 'footrank-14e9a.firebasestorage.app',
    measurementId: 'G-BSEQKHPNPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFt-WnwvrVPYhSpmkypwDthGELTnppH8',
    appId: '1:123604383744:android:4656e001fcf290e4d840e5',
    messagingSenderId: '123604383744',
    projectId: 'footrank-14e9a',
    storageBucket: 'footrank-14e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYdsM7xxeRG0xC-DgF8MsVUP1maI3XpM',
    appId: '1:123604383744:ios:1bbc2ca060d4932bd840e5',
    messagingSenderId: '123604383744',
    projectId: 'footrank-14e9a',
    storageBucket: 'footrank-14e9a.firebasestorage.app',
    iosBundleId: 'com.example.footrank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiYdsM7xxeRG0xC-DgF8MsVUP1maI3XpM',
    appId: '1:123604383744:ios:1bbc2ca060d4932bd840e5',
    messagingSenderId: '123604383744',
    projectId: 'footrank-14e9a',
    storageBucket: 'footrank-14e9a.firebasestorage.app',
    iosBundleId: 'com.example.footrank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQk19EcNUt3xOYK7iC97NoaOcfFD-y5qA',
    appId: '1:123604383744:web:8141088263630bb3d840e5',
    messagingSenderId: '123604383744',
    projectId: 'footrank-14e9a',
    authDomain: 'footrank-14e9a.firebaseapp.com',
    storageBucket: 'footrank-14e9a.firebasestorage.app',
    measurementId: 'G-TFYKY2Q4JH',
  );
}
